environments:
  D0001-ETM:
    web:
      farm:
        win:
          os_type: Windows
          sku_name: P1v3
          worker_count: 1
        lin:
          os_type: Linux
          sku_name: P1v3
          worker_count: 1

      web_app:
        web:
          os_type: windows
          deploy_type: code
          plan_ref: win
          windows_application_stack:
            current_stack: dotnet
            dotnet_version: v8.0
          app_settings:
            ASPNETCORE_ENVIRONMENT: Development

        api:
          os_type: linux
          deploy_type: container
          plan_ref: lin
          container:
            image_name: myacr.azurecr.io/etm-api:1.0.0
            registry_url: https://myacr.azurecr.io
            use_acr_mi: true
          app_settings:
            ASPNETCORE_ENVIRONMENT: Development
